# Environment Configuration
# This file defines the Azure ML environment settings

# Azure Subscription and Resource Details
azure:
  subscription_id: "f7694127-2f65-4c53-aaef-a2750f7337d3"
  resource_group: "defalt_resource_group"
  workspace_name: "FitwellWorkspace"
  location: "eastus"

# Compute Configuration
compute:
  default_compute_target: "test-cluster"
  vm_sizes:
    development: "Standard_DS11_v2"
    production: "Standard_DS12_v2"
  
# Storage Configuration  
storage:
  default_datastore: "workspaceblobstore"
  
# Environment Settings
environments:
  training:
    name: "used-cars-train-env"
    python_version: "3.7.5"
    
# Security Settings
security:
  authentication_method: "service_principal"
  
# Pipeline Settings
pipeline:
  default_timeout_minutes: 120
  enable_monitoring: true
  continue_on_step_failure: false
