$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: Used-Cars-Price-Prediction-Pipeline
experiment_name: used-cars-price-prediction
description: End-to-end-MLOps-pipeline-for-used-car-price-prediction

inputs:
  raw_data:
    type: uri_file
    path: azureml:used-cars-data-v2@latest

outputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  model_info_output_path:
    type: uri_folder

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:test-cluster
  continue_on_step_failure: false

jobs:
  prep_data:
    component:
      $schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
      type: command
      code: ./data-science/src
      command: >-
        python prep.py  
        --raw_data ${{inputs.raw_data}} 
        --train_data ${{outputs.train_data}}
        --test_data ${{outputs.test_data}} 
      environment: azureml:used-cars-train-env@latest
      inputs:
        raw_data:
          type: uri_file
      outputs:
        train_data:
          type: uri_folder
        test_data:
          type: uri_folder
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  sweep_step:
    type: sweep
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: mlflow_model
    sampling_algorithm: random
    trial:
      code: ./data-science/src
      command: >-
        python train.py
        --train_data ${{inputs.train_data}}
        --test_data ${{inputs.test_data}}
        --n_estimators ${{inputs.n_estimators}}
        --max_depth ${{inputs.max_depth}}
        --model_output ${{outputs.model_output}}
      environment: azureml:used-cars-train-env@latest
      inputs:
        train_data:
          type: uri_folder
        test_data:
          type: uri_folder
        n_estimators:
          type: integer
          default: 100
        max_depth:
          type: integer
          default: 10
      outputs:
        model_output:
          type: mlflow_model
    search_space:
      n_estimators:
        type: choice
        values: [10, 20, 30, 50]
      max_depth:
        type: choice
        values: [5, 10, 15, 20]
    objective:
      goal: minimize
      primary_metric: MSE
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200

  register_model:
    component:
      $schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
      type: command
      code: ./data-science/src
      command: >-
        python register.py 
        --model_name ${{inputs.model_name}} 
        --search_base "/mnt/azureml/cr/j"
        --model_info_output_path ${{outputs.model_info_output_path}}
        --train_data ${{inputs.train_data}}
      environment: azureml:used-cars-train-env@latest
      inputs:
        model_name:
          type: string
        train_data:
          type: uri_folder
      outputs:
        model_info_output_path:
          type: uri_folder
    inputs:
      model_name: "used_cars_price_prediction_model"
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}

