channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - azureml-mlflow==1.55.0
      - azure-ai-ml==1.12.0
      - pyarrow==12.0.0
      - scikit-learn==1.3.0
      - pandas==2.0.3
      - joblib==1.3.0
      - matplotlib==3.7.0
      - numpy==1.24.3