name: register-dataset

on:
  workflow_call:
    inputs:
      data_file:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      file_type:
        required: false
        type: string
        default: ""
      name:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ format('{{"clientId":"{0}","clientSecret":"{1}","subscriptionId":"{2}","tenantId":"{3}"}}', secrets.AZURE_CLIENT_ID, secrets.AZURE_CLIENT_SECRET, secrets.AZURE_SUBSCRIPTION_ID, secrets.AZURE_TENANT_ID) }}
      - name: install-extension
        run: az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: create-dataset-from-file
        if: ${{ inputs.file_type == ''}}
        run: |
          az ml data create --file ${{ inputs.data_file }} --name ${{ inputs.name }} --resource-group ${{ inputs.resource_group }} --workspace-name ${{ inputs.workspace_name }}
      - name: create-dataset-from-folder
        if: ${{ inputs.file_type == 'folder'}}
        run: |
          az ml data create --file ${{ inputs.data_file }} --name ${{ inputs.name }} --resource-group ${{ inputs.resource_group }} --workspace-name ${{ inputs.workspace_name }} --type uri_folder
